export const API_ENDPOINTS = Object.freeze({
  health: '/health',
  auth: {
    registerOwner: '/auth/register-owner',
    login: '/auth/login',
    pin: '/auth/pin',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    changePassword: '/auth/change-password',
    sessions: '/auth/sessions',
  },
  dashboard: {
    summary: '/dashboard',
  },
  company: '/companies/current',
  branches: '/branches',
  employees: '/employees',
  access: '/access',
  products: '/catalog/products',
  categories: '/catalog/categories',
  units: '/catalog/units',
  inventory: '/inventory/stocks',
  customers: '/customers',
  orders: '/orders',
  agents: '/agents',
  fulfillment: '/fulfillment',
  delivery: '/delivery/deliveries',
  invoices: '/invoices',
  payments: '/payments',
  finance: '/finance',
  returns: '/returns',
  reports: '/reports',
  notifications: '/notifications',
  settings: '/settings',
});
