export const ROLES = Object.freeze({
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
});

export const BUSINESS_OWNER_ROLES = [ROLES.OWNER, ROLES.ADMIN];
export const PLATFORM_AUTH_ROLES = [ROLES.OWNER, ROLES.ADMIN, ROLES.SUPER_ADMIN];
