export const TASK_STATUS = Object.freeze({
  ASSIGNED: "ASSIGNED",
  SEEN: "SEEN",
  ACCEPTED: "ACCEPTED",
  IN_PROGRESS: "IN_PROGRESS",
  WAITING: "WAITING",
  BLOCKED: "BLOCKED",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  OVERDUE: "OVERDUE",
});

export const APPROVAL_STATUS = Object.freeze({
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CHANGES_REQUESTED: "CHANGES_REQUESTED",
  CANCELLED: "CANCELLED",
});

export const ORDER_STATUS = Object.freeze({ DRAFT: "DRAFT", SUBMITTED: "SUBMITTED", CONFIRMED: "CONFIRMED", CANCELLED: "CANCELLED" });
export const FULFILLMENT_STATUS = Object.freeze({ NOT_STARTED: "NOT_STARTED", RESERVED: "RESERVED", PICKING: "PICKING", PICKED: "PICKED", PACKING: "PACKING", READY: "READY", PARTIAL: "PARTIAL", COMPLETED: "COMPLETED" });
export const DELIVERY_STATUS = Object.freeze({ PLANNED: "PLANNED", OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY", ARRIVED: "ARRIVED", DELIVERED: "DELIVERED", PARTIALLY_DELIVERED: "PARTIALLY_DELIVERED", FAILED: "FAILED", CANCELLED: "CANCELLED" });
export const PAYMENT_STATUS = Object.freeze({ PENDING: "PENDING", CONFIRMED: "CONFIRMED", FAILED: "FAILED", REFUNDED: "REFUNDED" });
